name: ci

on: push

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Install
        run: npm install -g yarn && yarn

      - name: Build
        run: yarn run build

      - name: Test
        run: yarn run test
