name: ci

on: push

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Install
        run: yarn

      - name: Build
        run: yarn run build

      - name: Test
        run: yarn run test
